service: talent-board-backend

provider:
  name: aws
  region: ${env:REGION, 'ap-southeast-1'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 30
  environment:
    SECRET_ARN:
      Ref: SecretsManager
    CLUSTER_ARN: "arn:aws:rds:#{AWS::Region}:#{AWS::AccountId}:cluster:#{AuroraRDSCluster}"
    DB_NAME: ${self:custom.AURORA.DB_NAME}
    REGION: ${self:provider.region}
    SERVICE_NAME: "${self:service}-${self:provider.stage}"
    STAGE: "${self:provider.stage, dev}"

plugins:
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  secretsManagerName: "aws-reskill-connection-${self:provider.stage}-${self:provider.region}"

functions:
  talentBoard: ${file(./Resources/LambdaResources/talentBoard.yml)}
  talentBoardCron: ${file(./Resources/LambdaResources/talentBoardCron.yml)}
