const industries = [
  "Information Technology and Services",
  "Hospital & Health Care",
  "Construction",
  "Education Management",
  "Retail",
  "Financial Services",
  "Accounting",
  "Computer Software",
  "Automotive",
  "Higher Education",
  "Marketing & Advertising",
  "Government Administration",
  "Banking",
  "Health, Welness & Fitness",
  "Real Estate",
  "Telecommunications",
  "Oil & Energy",
  "Food & Beverages",
  "Hospitality",
  "Mechanical or Industrial Engineering",
  "Electrical & Electronic Manufacturing",
  "Primary/Secondary Education",
  "Insurance",
  "Internet",
  "Human Resources",
  "Medical Practice",
  "Transportation/Trucking/Railroad",
  "Consumer Services",
  "Management Consulting",
  "Pharmaceuticals",
  "Civil Engineering",
  "Design",
  "Research",
  "Restaurants",
  "Logistics & Supply Chain",
  "Architecture & Planning",
  "Law Practice",
  "Apparel & Fashion",
  "Consumer Goods",
  "Facilities Services",
  "Food Production",
  "Non-profit Organization Management",
  "Entertainment",
  "Machinery",
  "Chemicals",
  "Arts & Crafts",
  "Wholesale",
  "Utilities",
  "Legal Services",
  "Farming",
  "Mining & Metals",
  "Airlines/Aviation",
  "Leisure, Travel & Turism",
  "Sporting Goods",
  "Building Materials",
  "Music",
  "Enviromental Services",
  "Professional Training & Coaching",
  "Medical Device",
  "Individual & Family Services",
  "Cosmetics",
  "Mental Health Care",
  "Aviation and Aerospace",
  "Staffing & Recruiting",
  "Industrial Automation",
  "Graphic Design",
  "Security & Investigations",
  "Import and Export",
  "Public Relations and Communications",
  "Textiles",
  "Military",
  "Broadcast Media",
  "Biotechnology",
  "Media Production",
  "Business Supplies & Equipment",
  "Computer Networking",
  "Writing & Editing",
  "Consumer Elecronics",
  "International Trade and Development",
  "Events Services",
  "Photography",
  "Renewables & Envirnoment",
  "Computer Hardware",
  "Civic and Social Organization",
  "Furniture",
  "Defense & Space",
  "Computer & Network Security",
  "Printing",
  "Fine Art",
  "Religious Institutions",
  "Investmend Management",
  "Law Enforcement",
  "Publishing",
  "Information Services",
  "Maritime",
  "Outsourcing/Offshoring",
  "Warehousing",
  "E-learning",
  "Executive Office",
  "Government Relations",
  "Animation",
  "Semiconducs",
  "Supermarkets",
  "Program Development",
  "Public Safety",
  "Plastics",
  "Alternative Medicine",
  "Performing Arts",
  "Online Media",
  "Motion Pictures & Film",
  "Commercial Real Estate",
  "Judiciary",
  "Packaging and Containers",
  "Luxury Goods & Jewelry",
  "Veterinary",
  "Computer Games",
  "Investment Banking",
  "Market Research",
  "International Affairs",
  "Wine & Spirits",
  "Newspapers",
  "Translation & Localisation",
  "Recreational Facilities & Services",
  "Sporting Goods",
  "Paper & Forest Products",
  "Capital Markets",
  "Public Policy",
  "Package/Freight Delivery",
  "Libraries",
  "Wireless",
  "Gambling & Casinos",
  "Venture Capital & Private Equity",
  "Glass, Ceramics & Concrete",
  "Philanthropy",
  "Ranching",
  "Dairy",
  "Museums and Institutions",
  "Shipbuilding",
  "Think Thanks",
  "Political Organization",
  "Fishery",
  "Fund-Raising",
  "Tobacco",
  "Railroad Manufacture",
  "Alternative Dispute Resolution",
  "Nanotechnology",
  "Legislative Office"
];

module.exports = {
  industries
};
